{
 "title": "Triathlon Participation Analytics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Nationality",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    \n    COUNT(*) as athlete_count,\n    \"country\"\nFROM public.athletes_df\nWHERE country IS NOT NULL\nGROUP BY country\nORDER BY athlete_count DESC;"
    }
   ]
  },
  {
   "title": "Age histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    age\nFROM public.athletes_df\nWHERE age IS NOT NULL\nORDER BY age;"
    }
   ]
  },
  {
   "title": "Top 10 Companies",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n   LEFT(company, 20)  as Company,\n    COUNT(*) as \"athlete_count\"\nFROM public.athletes_df\nWHERE company IS NOT NULL\nGROUP BY company\nORDER BY athlete_count DESC\nLimit 10\n;"
    }
   ]
  },
  {
   "title": "Athletes per Club",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    club,\n    COUNT(*) as \"athlete_count\"\nFROM public.athletes_df\nWHERE club IS NOT NULL\nGROUP BY club\nORDER BY athlete_count DESC;"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total_participants FROM public.athletes_df;"
    }
   ]
  },
  {
   "title": "Olympic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total_participants FROM public.athletes_df where contest_category_id = 1;"
    }
   ]
  },
  {
   "title": "Not Olympic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as total_participants FROM public.athletes_df where contest_category_id != 1;"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', created_at) AS time,\n  avg(athletes_count) as value\nFROM dataset_update_events\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Participants in wait list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', created_at) AS time,\n  avg(athletes_wait_list_count) as value\nFROM dataset_update_events\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Dataset updates",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \n    created_at,\n\tathletes_count,\n\tathletes_wait_list_count \nFROM public.dataset_update_events\nORDER BY created_at DESC;"
    }
   ]
  }
 ]
}